#!/bin/bash
RUN_VERSIONING=0

echo "running pre push hook..."


# Get current dir
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Run tests
echo "running tests..."
go test $CURRENT_DIR/..

## Builds docker image (and runs integration tests in the building process).
echo "building docker image (for integration tests)..."
docker build -f promgateway-service.dockerfile .

# Run versioning if branch is main branch Tag
CURRENT_BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
if [[ $CURRENT_BRANCH == "main" && RUN_VERSIONING == 1 ]]; then
    echo "versioning..."
    $CURRENT_DIR/scripts/update_version.sh
fi

# Run lint
